### ISSUE TITLE
What's THETA function?

### ISSUE THREAD

**Issue by pfalcon** [EiNSTeiN-/decompiler#10]
As used in:
~~~~
i@4 = THETA(i@0, i@4, ) + 1;
~~~~

It's used in context where PHI function is usually used (join several SSA variables into one): http://en.wikipedia.org/wiki/Static_single_assignment_form . vanEmmerik_ssa.pdf you give as a reference also used standard terminology of phi.

**Comment by EiNSTeiN-** [comment]
Same thing, I guess I need to review my ssa terminology

**Comment by pfalcon** [comment]
Well, if you target this project not as a personal hack, but for general community consumption (*), I suggest to not be afraid of global search&replace commit to make it more clear/accessible.

* And someone really should, and your project, being no.2 in my today's review list, looks pretty good for that (at least it does SSA and refers to a complete thesis of a known guy in the field). And fairly speaking, I don't have many more entries in my list :-(.

**Comment by EiNSTeiN-** [comment]
> Well, if you target this project not as a personal hack, but for general community consumption

That would be the goal but we're not there yet :)

> search&replace commit to make it more clear/accessible.

I will, thanks for the suggestion. You are not the first one to mention that I'm using theta instead of phi.

**Comment by EiNSTeiN-** [comment]
Fixed in 338cb8cbd68d179013ab83a302550a65855706d5

**Comment by pfalcon** [comment]
Thanks!
