### ISSUE TITLE
Unit tests not working

### ISSUE THREAD

**Issue by techvoltage** [EiNSTeiN-/decompiler#12]
I'm getting several errors while doing unit tests:
no module named ply.yacc
no module named expressions
..............................statements

**Comment by EiNSTeiN-** [comment]
> no module named ply.yacc

Did you install ply? See https://github.com/EiNSTeiN-/decompiler/blob/master/requirements.txt

> no module named expressions
> ..............................statements

Those are in the [src directory](https://github.com/EiNSTeiN-/decompiler/blob/master/src) so there is probably a problem with how you are running the unit tests.

**Comment by techvoltage** [comment]
Okay Thanks!
